const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const infoSchema = new Schema({
    name:{
        type:String,
        require:true
    },
    gender:{
        type:String,
        require:true
    },
    old:{
        type:Number,
        require:true
    },
    height:{
        type:Number,
        require:true
    },
    weight:{
        type:Number,
        require:true
    },
    skill:{
        type:String,
        require:true
    },
    phone:{
        type:Number,
        require:true
    },
    address:{
        type:String,
        require:true
    },
    img:{
        type:String,
        require:true
    },
    cloudinary_id:{
        type:String
    },
    description:{
        type:String,
        require:true
    },
    character:{
        type:String,
        require:true
    },
    appearance:{
        type:String,
        require:true
    },
    rate:{
        type:Number
    },
    lit:{
        type:Number
    },
    lat:{
        type:Number
    },
    rank_level:{
        type:Schema.Types.ObjectId,
        ref:'experiences'
    },
    rent_cost:{
        type:Number,
        default:1000
    },
    user:{
        type:Schema.Types.ObjectId,
        ref:'users'
    },
    createdAt:{
        type:Date,
        default: Date.now
    }
});

module.exports = mongoose.model('infos',infoSchema);